### ISSUE TITLE
ERROR in MdModule is not an NgModule

### ISSUE THREAD

**Issue by windmaomao** [yisraelx/ngx-showdown#1]
tried to install this but get this error after I import MdModule.

**Comment by yisraelx** [comment]
Maybe you did:
```typescript
import MdModule from 'ng2-md';
// or
import { default as MdModule } from 'ng2-md';
```
Instead:
```typescript
import { MdModule } from 'ng2-md';
```
You can see an example for use in [Plunker](https://plnkr.co/edit/0j8d9w).

If this is not the problem, please put here an example of code that leads to the problem and version of Angular, so that i able to figure out what is the problem and solve it.

**Comment by windmaomao** [comment]
thanks for the help. 

there might be something i used wrong with outdated package.json. I updated it and now, it's working.

**Comment by windmaomao** [comment]
ok, i still have this issue, i guess the problem is that i'm using angular-cli, it can not be built, and therefore gives ERROR in MdModule is not an NgModule, maybe angular-cli does uglify something. I have no idea. But currently i still have to roll back with my old showdown service version.

**Comment by yisraelx** [comment]
I found it related to compile with angular compiler, I fix it and released a new version,
Thanks

**Comment by windmaomao** [comment]
thanks a ton, it's fixed, i can build it now. Awesome.
