### ISSUE TITLE
doesn't support strikethrough

### ISSUE THREAD

**Issue by rcogal** [yisraelx/ngx-showdown#13]
Hi,

format: ~~ Scratch this. ~~
output: ~~Scratch this~~

tried the format above but it doesn't scratch the text.

**Comment by yisraelx** [comment]
In the default [showdown options](https://github.com/showdownjs/showdown/wiki/Showdown-Options), the [`strikethrough`](https://github.com/showdownjs/showdown/wiki/Showdown-Options#strikethrough) option is set to `false` , so you must set `strikethrough` to `true`  in order for it to work.

```ts
import { Component, NgModule } from '@angular/core';
import { ShowdownModule } from 'ngx-showdown';

@Component({
  selector: 'app',
  template: '<showdown>~~ Scratch this. ~~</showdown>'
})
export class AppComponent {}

@NgModule({
  declarations: [ AppComponent ],
  imports: [ ShowdownModule.forRoot({ strikethrough: true }) ]
})
export class AppModule {}
```
Or in the template
```html
<showdown strikethrough>~~ Scratch this. ~~</showdown>
```


-----
You can see `strikethrough` working in the [demo](https://yisraelx.github.io/ngx-showdown/#emphasis-).

**Comment by rcogal** [comment]
this resolves the problem. thank you, @yisraelx
