### ISSUE TITLE
How do I use showdown extensions

### ISSUE THREAD

**Issue by windmaomao** [yisraelx/ngx-showdown#2]
ex. 

var converter = new showdown.Converter({extensions: ['prettify']}),

**Comment by yisraelx** [comment]
'MdDirective', 'MdPipe' and 'MdConverter' is extends from 'showdown.Converter',
on Angular create them, it takes the value of 'ConverterOptions' and injects it to their constructor.
```typescript
let options: ConverterOptions | IConverterConstructorOptions = this.injector.get(ConverterOptions);
let converter = new showdown.Converter(options);
```
How can you set up your 'ConverterOptions':
```typescript
import { NgModule, Component } from '@angular/core';
import { ConverterOptions } from 'ng2-md';
export class MyConverterOptions extends ConverterOptions{
 constructor(){
  super({ extensions: ['prettify'] })
 }
}

// for module
@NgModule({
providers: [
  { provide: ConverterOptions, useClass: MyConverterOptions  }
 ]
})
export class SomeApp{

}

// for component
@Component({
 providers: [
  { provide: ConverterOptions, useClass: MyConverterOptions  }
 ]
})
export class SomeComponent{

}
```
Or
```typescript
import { NgModule, Component } from '@angular/core';
import { ConverterOptions } from 'ng2-md';

// for module
@NgModule({
providers: [
  { provide: ConverterOptions, useValue: { extensions: ['prettify']} }
 ]
})
export class SomeApp{

}
// for component
@Component({
 providers: [
  { provide: ConverterOptions, useValue: { extensions: ['prettify']} }
 ]
})
export class SomeComponent{

}
```
All options can be change after creation by using binding but the extensions is not possible to binding, but  can be selected MdDirective with ViewChild or Query (by selector) and use the parant method: 
```typescript
import { ViewChild } from '@angular/core';
import { MdDirective } from 'ng2-md';

export class SomeComponent{
 @ViewChild(MdDirective) converter: MdDirective;
 // ...
  this.converter.useExtension('prettify');
  this.converter.removeExtension('prettify');
 // ...
}
```
'extensions: string[]' declare is missing in ConverterOptions class (and new showdown options) i will add it next release.
and maybe the class 'ConverterOptions' name need to be 'ConverterConstructorOptions' (more suitable).

**Comment by windmaomao** [comment]
thanks for the answer, appreciate it. In the meantime, i actually get it working via another module.

```
  import { HighlightJsModule }    from 'angular2-highlight-js';
@NgModule({
  imports: [
    HighlightJsModule,
```

and then inside the template,

```
    <md [value]="selected.description" [options]="{ parseImgDimension: true }"  highlight-js-content="pre code"></md>
```

this works great for now.

**Comment by yisraelx** [comment]
I made the changes:
@7c85fcbcd75135fee0020977df8443f084d487f7 - rename converter options interfaces
@678d169a9b9000532528a020ff76dfb18682601c - update ConverterOptions to current Showdown options

**Comment by yisraelx** [comment]
I made the changes:
@7c85fcbcd75135fee0020977df8443f084d487f7 - rename converter options interfaces
@678d169a9b9000532528a020ff76dfb18682601c - update ConverterOptions to current Showdown options
