### ISSUE TITLE
Parent child module

### ISSUE THREAD

**Issue by windmaomao** [yisraelx/ngx-showdown#3]
@yisraelx, thanks for the component. Very nice.

I run into an issue today. If I define MdModule and include it in AppModule 

```
@NgModule({
  imports: [
    BrowserModule,

    // Third party
    MdModule,

    // Features
    BlogModule
  ],
})
export class AppModule { }
```

I couldn't get `md` directive inside BlogModule. Am I doing anything wrong, because I normally get this type of inheritance. I did notice some other module is using

```
    NgLoadingBarModule.forRoot(),
```

I wonder if this is the reason here.

**Comment by yisraelx** [comment]
I think there is no inheritance of the components between the modules, and each module you must provide his own components.

```typescript
import { MdModule } from 'ng2-md';
import { NgModule } from '@angular/core';
@NgModule({
  imports: [ NgModule ]
})
export class BlogModule{}

@NgModule({
  imports: [
    BrowserModule,

    // Third party
    MdModule,

    // Features
    BlogModule
  ],
})
export class AppModule { }
```

And [forRoot method](https://angular.io/docs/ts/latest/guide/ngmodule.html#core-for-root) is for an easy configuration of the module.

After the issue #2 , I was thinking maybe add it for easy configuration of 'ConverterOptions'.

```typescript
import { MdModule, ConverterOptions, IConverterConstructorOptions } from 'ng2-md';
import { NgModule } from '@angular/core';

@NgModule({
  imports: [
    MdModule.forRoot({...} as ConverterOptions | IConverterConstructorOptions)
  ]
})
export class AppModule { }
```
Maybe I added it to the next release.

**Comment by yisraelx** [comment]
I made the change:
@56f2186795345dca7f949f4b657a3f689d654426 -  add 'forRoot' method to MdModule
